#STAGE 1
FROM node:lts-alpine3.16 as builder

#Set working directory
WORKDIR /usr/src/app
#Copy Package.json To Docker Image
COPY package.json .
#Install Package Dependency
RUN npm install --quiet
#Copy Context To Docker Image
COPY . .
# ⚠️ Fix lỗi OpenSSL từ Node.js v17+
ENV NODE_OPTIONS=--openssl-legacy-provider
# Build Package
RUN npm run build

#STAGE 2
FROM nginx:1.23.1
#Set working directory
WORKDIR /usr/share/nginx/html
#Remove nginx default file and configuration
RUN rm -rf /usr/share/nginx/html/*
#Copy Build From Builder image
COPY --from=builder /usr/src/app/build /usr/share/nginx/html
#Expose Image PORT
EXPOSE 80
#Start Nginx Server
CMD ["nginx", "-g", "daemon off;"]
